// lz77.hpp - LZ77/BWT preprocessing for the block encoder.
//
// ZPAQ-NG - Copyright (c) 2026 Erick de S.C. Araujo. Unlicense.
//
// Faithful port of libzpaq.cpp's e8e9, LZBuffer, lg, nbits, and itos
// (lines 6436-6884). LZBuffer implements the lossless reversible
// transforms used before context modeling: variable length LZ77 (level 1),
// byte aligned LZ77 (level 2), and Burrows-Wheeler (level 3), optionally
// preceded by the E8E9 executable transform. The inverse transforms are the
// PCOMP programs generated by makeConfig and run by the PostProcessor.

#ifndef ZPAQ_NG_COMPRESSION_LZ77_HPP
#define ZPAQ_NG_COMPRESSION_LZ77_HPP

#include <cstdint>
#include <string>
#include <vector>

#include "core/types.hpp"
#include "io/streams.hpp"

namespace zpaq_ng::compression {

// Convert a non-negative number to a decimal string of at least n digits.
std::string itos(int64_t x, int n = 1);

// floor(log2(x)) + 1 = number of bits excluding leading zeros (0..32).
int lg(unsigned x);

// Number of 1 bits in x.
int nbits(unsigned x);

// E8E9 transform of buf[0..n-1] to improve compression of .exe and .dll.
// Patterns (E8|E9 xx xx xx 00|FF) at offset i replace the 3 middle bytes
// with x+i mod 2^24, LSB first, reading backward. In-place.
void e8e9(u8* buf, int n);

// LZ77/BWT preprocessor producing a byte stream that the PCOMP program
// from makeConfig turns back into the original data. A Reader over the
// encoded output.
//
// args follow makeConfig's convention:
//   [0] log2 buffer size in MB
//   [1] level (1=var. length, 2=byte aligned, 3=BWT) + 4 if E8E9
//   [2] lz77 minimum match length / context order
//   [3] higher context order to search first (0 = none)
//   [4] log2 hash bucket size (number of searches)
//   [5] log2 hash table size; 21+args[0] means a suffix array is used
//   [6] secondary context look ahead
// sap is an optional external suffix array (same size as input). If
// supplied and args[0]=5..7 the input is assumed to be already E8E9'd.
class LZBuffer : public io::Reader {
public:
  LZBuffer(const u8* in, size_t n, const int args[9],
           const unsigned* sap = nullptr);

  int get() override {
    int c = -1;
    if (rpos_ == wpos_) fill();
    if (rpos_ < wpos_) c = buf_[rpos_++];
    if (rpos_ == wpos_) rpos_ = wpos_ = 0;
    return c;
  }

  std::size_t read(char* p, std::size_t n) override;

private:
  std::vector<unsigned> ht_;    // hash table, confirm in low bits, or SA+ISA
  const unsigned char* in_;     // input pointer
  const int checkbits_;         // hash confirmation size or lg(ISA size)
  const int level_;             // 1=var length, 2=byte aligned, 3=BWT
  const unsigned htsize_;       // size of hash table
  const unsigned n_;            // input length
  unsigned i_ = 0;              // current location in in
  const unsigned min_match_;    // minimum match length
  const unsigned min_match2_;   // second context order or 0
  const unsigned max_match_;    // longest match length allowed
  const unsigned max_literal_;  // longest literal length allowed
  const unsigned lookahead_;    // second context look ahead
  unsigned h1_ = 0, h2_ = 0;    // low, high order context hashes
  const unsigned bucket_;       // number of matches to search per hash - 1
  const unsigned shift1_, shift2_;  // how far to shift h1, h2 per hash
  const unsigned min_match_both_;   // max(min_match, min_match2)+4
  const unsigned rb_;           // number of level 1 r bits in match code
  unsigned bits_ = 0;           // pending output bits (level 1)
  unsigned nbits_ = 0;          // number of bits in bits
  unsigned rpos_ = 0, wpos_ = 0;
  unsigned idx_ = 0;            // BWT index
  const unsigned* sa_ = nullptr;  // suffix array
  unsigned* isa_ = nullptr;     // inverse suffix array

  enum { BUFSIZE = 1 << 14 };
  unsigned char buf_[BUFSIZE];

  void write_literal(unsigned i, unsigned& lit);
  void write_match(unsigned len, unsigned off);
  void fill();

  // Write k bits of x.
  void putb(unsigned x, int k) {
    x &= (1u << k) - 1;
    bits_ |= x << nbits_;
    nbits_ += k;
    while (nbits_ > 7) {
      buf_[wpos_++] = bits_;
      bits_ >>= 8;
      nbits_ -= 8;
    }
  }

  // Write the last byte.
  void flush() {
    if (nbits_ > 0) buf_[wpos_++] = bits_;
    bits_ = nbits_ = 0;
  }

  // Write 1 byte.
  void put(int c) { buf_[wpos_++] = static_cast<unsigned char>(c); }
};

} // namespace zpaq_ng::compression

#endif // ZPAQ_NG_COMPRESSION_LZ77_HPP